"""add matching rule and recon summary models

Revision ID: 2989ca5179c5
Revises: 002_add_transaction_types
Create Date: 2025-12-18 14:58:11.771201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2989ca5179c5'
down_revision: Union[str, Sequence[str], None] = '002_add_transaction_types'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atm_transactions', 'datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('atm_transactions', 'rrn',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('flexcube_transactions', 'fc_txn_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('flexcube_transactions', 'rrn',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('flexcube_transactions', 'stan',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('flexcube_transactions', 'account_masked',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('flexcube_transactions', 'dr',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('flexcube_transactions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('flexcube_transactions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('flexcube_transactions', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('flexcube_transactions', 'cr')
    op.create_index(op.f('ix_matching_rules_id'), 'matching_rules', ['id'], unique=False)
    op.create_index(op.f('ix_recon_matching_summary_id'), 'recon_matching_summary', ['id'], unique=False)
    op.alter_column('switch_transactions', 'rrn',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('switch_transactions', 'responsecode',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('switch_transactions', 'authid',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('switch_transactions', 'authid',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('switch_transactions', 'responsecode',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('switch_transactions', 'rrn',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_recon_matching_summary_id'), table_name='recon_matching_summary')
    op.drop_index(op.f('ix_matching_rules_id'), table_name='matching_rules')
    op.add_column('flexcube_transactions', sa.Column('cr', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.alter_column('flexcube_transactions', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('flexcube_transactions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('flexcube_transactions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('flexcube_transactions', 'dr',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('flexcube_transactions', 'account_masked',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('flexcube_transactions', 'stan',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('flexcube_transactions', 'rrn',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('flexcube_transactions', 'fc_txn_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('atm_transactions', 'rrn',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('atm_transactions', 'datetime',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
